[build.environment]
  GIT_CLONE_FLAGS = "--no-recurse-submodules"

[build]
  base = "apps/client"
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200